### ISSUE TITLE
Colon Syntax in DependencyInjection/Compiler/RegisterFormResourcePass.php

### ISSUE THREAD

**Issue by Defcon0** [bresam/ivory-google-map-bundle#1]
Hello,

we switched to your bundle in our bundle: https://github.com/heimrichhannot/contao-google-maps-bundle .

When using with symfony 4 we're getting the following error because of the colon syntax used in `DependencyInjection/Compiler/RegisterFormResourcePass.php`:

```
//...
        if ($container->hasParameter($parameter = 'twig.form.resources')) {
            $container->setParameter(
                $parameter,
                array_merge(
                    ['IvoryGoogleMapBundle:Form:place_autocomplete_widget.html.twig'],
                    $container->getParameter($parameter)
                )
            );
        }
    }
}

```

Error:

```
Template reference "IvoryGoogleMapBundle:Form:place_autocomplete_widget.html.twig" not found, did you mean "@IvoryGoogleMap/Form/place_autocomplete_widget.html.twig"?
```

When changing it to

```
['@IvoryGoogleMap/Form/place_autocomplete_widget.html.twig'],
```

it works.

To my knowledge the @-syntax is available for symfony 3 and 4, so we could change it as described above, couldn't we?

Thanks in advance.

bye Defcon0

**Comment by bresam** [comment]
Hi @Defcon0 
Sorry, didn't get a notification for your message.

I will check this soon.

**Comment by bresam** [comment]
@Defcon0  Newest version is 3.0.5, hope this fixes your issue?

**Comment by Defcon0** [comment]
Looks good. Thanks, I‘ll test it.
