### ISSUE TITLE
Symfony project unittests broken because all services are public

### ISSUE THREAD

**Issue by sandermarechal** [bresam/ivory-google-map-bundle#11]
Your bundle registers this compiler pass: DependencyInjection/Compiler/PublicForTestsCompilerPass.php

This breaks the unittests of many applications that use the GoogleMapsBundle. Symfony only removes a service if it is not used and not public. Your compiler pass marks all services (not just those in your bundle) as public. Symfony will no longer remove them. Compiling the container fails (because often those unused services are placeholders, like "translator.logging" when logging is disabled) and all unittests fail.

Marking all services as public is a really bad idea. Please fix.

**Comment by Chris53897** [comment]
I guess this could be fixed by

`class PublicForTestsCompilerPass implements CompilerPassInterface
{
    public function process(ContainerBuilder $container): void
    {
        if (!$this->isPHPUnit()) {
            return;
        }

        foreach ($container->getDefinitions() as $definition) {

            if(str_contains($definition->getClass(), 'Ivory\GoogleMapBundle') ||
               str_contains($definition->getClass(), 'Ivory\GoogleMap')  ||
               str_contains($definition->getClass(), 'Ivory\Serializer'))
            {
             $definition->setPublic(true);
            }
        }
    }

    private function isPHPUnit(): bool
    {
        // there constants are defined by PHPUnit
        return defined('PHPUNIT_COMPOSER_INSTALL') || defined('__PHPUNIT_PHAR__');
    }
}`

**Comment by dunglas** [comment]
At least you should mark the services as public only in your own test suite (in the kernel loaded by your functional tests for instance), to not impact all projects requiring this bundle.

For instance, this Compiler Pass breaks the test suite of all projects using the Translator component.

**Comment by bresam** [comment]
Fixed as proposed by @Chris53897

**Comment by sandermarechal** [comment]
Thank you!
