### ISSUE TITLE
Compatibility with Symfony 6

### ISSUE THREAD

**Issue by cbeyer** [bresam/ivory-google-map-bundle#12]
How to use this great bundle with Symfony 6 ?

https://packagist.org/packages/ivory/google-map-bundle#3.0.8 => require symfony/framework-bundle: ^3.0 || ^4.0 || ^5.0

:(

**Comment by bresam** [comment]
This could be made possible by a pull request from your side :-)

**Comment by cbeyer** [comment]
Of course :)
But my skills are too limited :/

**Comment by bresam** [comment]
Updated
