### ISSUE TITLE
Symfony 4.4 deprecations

### ISSUE THREAD

**Issue by cbeyer** [bresam/ivory-google-map-bundle#2]
Hi, I have a SF4.4 project and a lot a deprecations like
`The "Symfony\Component\Config\Definition\Builder\TreeBuilder::root()" method called for the "business_account" configuration is deprecated since Symfony 4.3, pass the root name to the constructor instead.`

I think they come from this bundle. My question is: should this bundle be full SF4.4 compatible ?

Thanks !

**Comment by bresam** [comment]
We use this Bundle on several customer projects with Symfony 4.4.
I don't know about any breaking deprecations yet.

If you can give more informations i will check this.

**Comment by cbeyer** [comment]
Here some screenshots, I hope this will help you

![Capture d’écran 2021-02-14 à 22 25 07](https://user-images.githubusercontent.com/1151497/107889548-ad732b80-6f13-11eb-8ddf-3addcec31420.png)

![Capture d’écran 2021-02-14 à 22 25 55](https://user-images.githubusercontent.com/1151497/107889554-b49a3980-6f13-11eb-927e-ace43d8b4d50.png)

Composer.json : ivory/google-map-bundle 3.0.4 - ivory/google-map 3.0.4

**Comment by thorau** [comment]
Would be great to fix the mentioned deprecations.

**Comment by bresam** [comment]
@thorau, @cbeyer Please create a PR which fixes this issue.
Will check and merge it asap.

@cbeyer Yes it should be fully SF4 compatible, but there are several deprecations.

**Comment by thorau** [comment]
@bresam Do I have to fork the repo or could I push a new branch for PR?

**Comment by bresam** [comment]
Thank you, merged and fixed unittests and code coverage

**Comment by cbeyer** [comment]
Thanks ! Now I have same deprecations on https://github.com/bresam/ivory-serializer-bundle/ ;)

**Comment by bresam** [comment]
@cbeyer Just updated and fixed deprecations and unittests on the ivory/serializer-bundle package.
