### ISSUE TITLE
Remove templateing ?

### ISSUE THREAD

**Issue by Chris53897** [bresam/ivory-google-map-bundle#22]
This is deprecated and twig is already there.
How much work is it?

@bresam I guess you already are useing twig. Is that correct?

**Comment by bresam** [comment]
You mean the Helpers in Templating folder and Twig Extensions?
I think we can't just get rid of them.
It's kind of the main purpose of the bundle (beside services initialization and stuff like that).

What of that is deprecated?

**Comment by Chris53897** [comment]
I did thought, that the whole component is deprecated. Because it, is one of the components that hat is stucked at 6.4
This deprecation warnings are there at the moment.

```
1x: Since symfony/templating 6.4: "Symfony\Component\Templating\Helper\Helper" is deprecated since version 6.4 and will be removed in 7.0. Use Twig instead.
    1x in ApiHelperTest::setUp from Ivory\GoogleMapBundle\Tests\Templating

  1x: Since symfony/templating 6.4: "Symfony\Component\Templating\Helper\HelperInterface" is deprecated since version 6.4 and will be removed in 7.0. Use Twig instead.
    1x in ApiHelperTest::setUp from Ivory\GoogleMapBundle\Tests\Templating
```

**Comment by bresam** [comment]
If that's the case i think it's a lot of work.
Cause these Helpers are instantiated by
\Ivory\GoogleMapBundle\DependencyInjection\Compiler\RegisterHelperListenerPass where i had todo a hack and bring back some deprecated functionality. When these are not loaded, absolutely nothing works anymore.
As i have seen, egeloen made an intense usage of the dispatcher. Didn't get that deep down the rabbit hole but currently expecting a lot of changes.

**Comment by Chris53897** [comment]
I guess these are not the same helpers.
This repo actual supports the PHPEngine (which is deprecated) and Twig.
I want of course keep the Twig functionality.

**Comment by Chris53897** [comment]
Looks i was right with the deprecation of the whole component.
https://github.com/symfony/templating/commit/862776a4594c3e863c23f58636effc94963a453f
