### ISSUE TITLE
composer require ivory/google-map-bundle doesnt work

### ISSUE THREAD

**Issue by JasonAfs** [bresam/ivory-google-map-bundle#6]
Hi im trying to install your bundle but i can't i got this error:
![image](https://user-images.githubusercontent.com/70891385/150973898-0b8c56ad-6943-421a-9291-06470d710d64.png)
Can you help me ? (sorry for my english) thx!

**Comment by bresam** [comment]
Hi @JasonAfs 

Thank you for contacting me.
Which Symfony version do you use?
I will check it.

**Comment by JasonAfs** [comment]
hi thx! I’m using symfony 5.4

Envoyé de mon iPhone

**Comment by rudireg** [comment]
I suppose that, twig version is too old.

**Comment by JasonAfs** [comment]
my twig version? or the version that the bundle use?
thx!
