### ISSUE TITLE
Not compatibel with Symfony 3

### ISSUE THREAD

**Issue by sandermarechal** [bresam/ivory-google-map-bundle#8]
Your composer.json says you're still compatible with Symfony 3, but it's not. Commit 0188f0a47bec8b3d5881889ffde1f484803abe8d from PR #2 broke compatibility with Symfony 3, specifically the `getRootNode()` call in Configuration.php.

**Comment by bresam** [comment]
okay, sorry for that. you can reduce the version you install or even better upgrade to sf5 / sf6
